# About me

name: Vương Vũ Duy


on:
 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

domain: TamadoDeyui4566.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://TamadoDeyui4566.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /Translates/      # place folder name if the site is served in a subfolder

baseurl: /jekyll_tutorial
url: https://TamadoDeyui.github.io/duyvuong4566.github.io/

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Xin chào, tôi là DeyuiPVZ. Cảm ơn bạn đã ghé thăm!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
